import { CountriesTimeZoneInterface } from './src/interface/countries.time.zone.interface';
export const countriesTimeZone: CountriesTimeZoneInterface[] =
	[
		{
			idCountry: 1,
			utc: '	UTC-11	',
			timeZone: '	Pacific/Midway	',
			country: '	United States Minor Outlying Islands	',
			flagCode: '	us	',
		},
		{
			idCountry: 2,
			utc: '	UTC-11	',
			timeZone: '	Pacific/Pago_Pago	',
			country: '	American Samoa	',
			flagCode: '	ws	',
		},
		{
			idCountry: 3,
			utc: '	UTC-10	',
			timeZone: '	America/Adak	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 4,
			utc: '	UTC-10	',
			timeZone: '	Pacific/Honolulu	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 5,
			utc: '	UTC-10	',
			timeZone: '	Pacific/Rarotonga	',
			country: '	Cook Islands	',
			flagCode: '	ck	',
		},
		{
			idCountry: 6,
			utc: '	UTC-10	',
			timeZone: '	Pacific/Tahiti	',
			country: '	French Polynesia	',
			flagCode: '	pf	',
		},
		{
			idCountry: 7,
			utc: '	UTC-9:30	',
			timeZone: '	Pacific/Marquesas	',
			country: '	French Polynesia	',
			flagCode: '	pf	',
		},
		{
			idCountry: 8,
			utc: '	UTC-9	',
			timeZone: '	America/Anchorage	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 9,
			utc: '	UTC-9	',
			timeZone: '	America/Juneau	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 10,
			utc: '	UTC-9	',
			timeZone: '	America/Metlakatla	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 11,
			utc: '	UTC-9	',
			timeZone: '	America/Nome	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 12,
			utc: '	UTC-9	',
			timeZone: '	America/Sitka	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 13,
			utc: '	UTC-9	',
			timeZone: '	America/Yakutat	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 14,
			utc: '	UTC-9	',
			timeZone: '	Pacific/Gambier	',
			country: '	French Polynesia	',
			flagCode: '	pf	',
		},
		{
			idCountry: 15,
			utc: '	UTC-8	',
			timeZone: '	America/Los_Angeles	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 16,
			utc: '	UTC-8	',
			timeZone: '	America/Tijuana	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 17,
			utc: '	UTC-8	',
			timeZone: '	America/Vancouver	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 18,
			utc: '	UTC-8	',
			timeZone: '	Pacific/Pitcairn	',
			country: '	Pitcairn	',
			flagCode: '	pn	',
		},
		{
			idCountry: 19,
			utc: '	UTC-7	',
			timeZone: '	America/Boise	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 20,
			utc: '	UTC-7	',
			timeZone: '	America/Cambridge_Bay	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 21,
			utc: '	UTC-7	',
			timeZone: '	America/Ciudad_Juarez	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 22,
			utc: '	UTC-7	',
			timeZone: '	America/Creston	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 23,
			utc: '	UTC-7	',
			timeZone: '	America/Dawson	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 24,
			utc: '	UTC-7	',
			timeZone: '	America/Dawson_Creek	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 25,
			utc: '	UTC-7	',
			timeZone: '	America/Denver	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 26,
			utc: '	UTC-7	',
			timeZone: '	America/Edmonton	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 27,
			utc: '	UTC-7	',
			timeZone: '	America/Fort_Nelson	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 28,
			utc: '	UTC-7	',
			timeZone: '	America/Hermosillo	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 29,
			utc: '	UTC-7	',
			timeZone: '	America/Inuvik	',
			country: '	Canada	',
			flagCode: '	cs	',
		},
		{
			idCountry: 30,
			utc: '	UTC-7	',
			timeZone: '	America/Mazatlan	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 31,
			utc: '	UTC-7	',
			timeZone: '	America/Phoenix	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 32,
			utc: '	UTC-7	',
			timeZone: '	America/Whitehorse	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 33,
			utc: '	UTC-7	',
			timeZone: '	America/Yellowknife	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 34,
			utc: '	UTC-6	',
			timeZone: '	America/Bahia_Banderas	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 35,
			utc: '	UTC-6	',
			timeZone: '	America/Belize	',
			country: '	Belize	',
			flagCode: '	mz	',
		},
		{
			idCountry: 36,
			utc: '	UTC-6	',
			timeZone: '	America/Chicago	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 37,
			utc: '	UTC-6	',
			timeZone: '	America/Chihuahua	',
			country: '	Mexico	',
			flagCode: 'mx',
		},
		{
			idCountry: 38,
			utc: '	UTC-6	',
			timeZone: '	America/Costa_Rica	',
			country: '	Costa Rica	',
			flagCode: '	cr	',
		},
		{
			idCountry: 39,
			utc: '	UTC-6	',
			timeZone: '	America/El_Salvador	',
			country: '	El Salvador	',
			flagCode: '	sv	',
		},
		{
			idCountry: 40,
			utc: '	UTC-6	',
			timeZone: '	America/Guatemala	',
			country: '	Guatemala	',
			flagCode: '	gt	',
		},
		{
			idCountry: 41,
			utc: '	UTC-6	',
			timeZone: '	America/Indiana/Knox	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 42,
			utc: '	UTC-6	',
			timeZone: '	America/Indiana/Tell_City	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 43,
			utc: '	UTC-6	',
			timeZone: '	America/Managua	',
			country: '	Nicaragua	',
			flagCode: '	ni	',
		},
		{
			idCountry: 44,
			utc: '	UTC-6	',
			timeZone: '	America/Matamoros	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 45,
			utc: '	UTC-6	',
			timeZone: '	America/Menominee	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 46,
			utc: '	UTC-6	',
			timeZone: '	America/Merida	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 47,
			utc: '	UTC-6	',
			timeZone: '	America/Mexico_City	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 48,
			utc: '	UTC-6	',
			timeZone: '	America/Monterrey	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 49,
			utc: '	UTC-6	',
			timeZone: '	America/North_Dakota/Beulah	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 50,
			utc: '	UTC-6	',
			timeZone: '	America/North_Dakota/Center	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 51,
			utc: '	UTC-6	',
			timeZone: '	America/North_Dakota/New_Salem	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 52,
			utc: '	UTC-6	',
			timeZone: '	America/Ojinaga	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 53,
			utc: '	UTC-6	',
			timeZone: '	America/Rankin_Inlet	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 54,
			utc: '	UTC-6	',
			timeZone: '	America/Regina	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 55,
			utc: '	UTC-6	',
			timeZone: '	America/Resolute	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 56,
			utc: '	UTC-6	',
			timeZone: '	America/Swift_Current	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 57,
			utc: '	UTC-6	',
			timeZone: '	America/Tegucigalpa	',
			country: '	Honduras	',
			flagCode: '	hn	',
		},
		{
			idCountry: 58,
			utc: '	UTC-6	',
			timeZone: '	America/Winnipeg	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 59,
			utc: '	UTC-6	',
			timeZone: '	Pacific/Easter	',
			country: '	Chile	',
			flagCode: '	cl	',
		},
		{
			idCountry: 60,
			utc: '	UTC-6	',
			timeZone: '	Pacific/Galapagos	',
			country: '	Ecuador	',
			flagCode: '	ec	',
		},
		{
			idCountry: 61,
			utc: '	UTC-5	',
			timeZone: '	America/Atikokan	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 62,
			utc: '	UTC-5	',
			timeZone: '	America/Bogota	',
			country: '	Colombia	',
			flagCode: '	co	',
		},
		{
			idCountry: 63,
			utc: '	UTC-5	',
			timeZone: '	America/Cancun	',
			country: '	Mexico	',
			flagCode: '	mx	',
		},
		{
			idCountry: 64,
			utc: '	UTC-5	',
			timeZone: '	America/Cayman	',
			country: '	Cayman Islands	',
			flagCode: '	ky	',
		},
		{
			idCountry: 65,
			utc: '	UTC-5	',
			timeZone: '	America/Detroit	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 66,
			utc: '	UTC-5	',
			timeZone: '	America/Eirunepe	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 67,
			utc: '	UTC-5	',
			timeZone: '	America/Grand_Turk	',
			country: '	Turks and Caicos Islands	',
			flagCode: '	tc	',
		},
		{
			idCountry: 68,
			utc: '	UTC-5	',
			timeZone: '	America/Guayaquil	',
			country: '	Ecuador	',
			flagCode: '	ec	',
		},
		{
			idCountry: 69,
			utc: '	UTC-5	',
			timeZone: '	America/Havana	',
			country: '	Cuba	',
			flagCode: '	cu	',
		},
		{
			idCountry: 70,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Indianapolis	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 71,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Marengo	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 72,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Petersburg	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 73,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Vevay	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 74,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Vincennes	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 75,
			utc: '	UTC-5	',
			timeZone: '	America/Indiana/Winamac	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 76,
			utc: '	UTC-5	',
			timeZone: '	America/Iqaluit	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 77,
			utc: '	UTC-5	',
			timeZone: '	America/Jamaica	',
			country: '	Jamaica	',
			flagCode: '	jm	',
		},
		{
			idCountry: 78,
			utc: '	UTC-5	',
			timeZone: '	America/Kentucky/Louisville	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 79,
			utc: '	UTC-5	',
			timeZone: '	America/Kentucky/Monticello	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 80,
			utc: '	UTC-5	',
			timeZone: '	America/Lima	',
			country: '	Peru	',
			flagCode: '	pe	',
		},
		{
			idCountry: 81,
			utc: '	UTC-5	',
			timeZone: '	America/Nassau	',
			country: '	Bahamas	',
			flagCode: '	bs	',
		},
		{
			idCountry: 82,
			utc: '	UTC-5	',
			timeZone: '	America/New_York	',
			country: '	United States	',
			flagCode: '	us	',
		},
		{
			idCountry: 83,
			utc: '	UTC-5	',
			timeZone: '	America/Panama	',
			country: '	Panama	',
			flagCode: '	pa	',
		},
		{
			idCountry: 84,
			utc: '	UTC-5	',
			timeZone: '	America/Port-au-Prince	',
			country: '	Haiti	',
			flagCode: '	ht	',
		},
		{
			idCountry: 85,
			utc: '	UTC-5	',
			timeZone: '	America/Rio_Branco	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 86,
			utc: '	UTC-5	',
			timeZone: '	America/Toronto	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 87,
			utc: '	UTC-4	',
			timeZone: '	America/Anguilla	',
			country: '	Anguilla	',
			flagCode: '	ai	',
		},
		{
			idCountry: 88,
			utc: '	UTC-4	',
			timeZone: '	America/Antigua	',
			country: '	Antigua and Barbuda	',
			flagCode: '	ag	',
		},
		{
			idCountry: 89,
			utc: '	UTC-4	',
			timeZone: '	America/Aruba	',
			country: '	Aruba	',
			flagCode: '	aw	',
		},
		{
			idCountry: 90,
			utc: '	UTC-4	',
			timeZone: '	America/Asuncion	',
			country: '	Paraguay	',
			flagCode: '	py	',
		},
		{
			idCountry: 91,
			utc: '	UTC-4	',
			timeZone: '	America/Barbados	',
			country: '	Barbados	',
			flagCode: '	bb	',
		},
		{
			idCountry: 92,
			utc: '	UTC-4	',
			timeZone: '	America/Blanc-Sablon	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 93,
			utc: '	UTC-4	',
			timeZone: '	America/Boa_Vista	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 94,
			utc: '	UTC-4	',
			timeZone: '	America/Campo_Grande	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 95,
			utc: '	UTC-4	',
			timeZone: '	America/Caracas	',
			country: '	Venezuela	',
			flagCode: '	ve	',
		},
		{
			idCountry: 96,
			utc: '	UTC-4	',
			timeZone: '	America/Cuiaba	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 97,
			utc: '	UTC-4	',
			timeZone: '	America/Curacao	',
			country: '	Curacao	',
			flagCode: '	cw	',
		},
		{
			idCountry: 98,
			utc: '	UTC-4	',
			timeZone: '	America/Dominica	',
			country: '	Dominica	',
			flagCode: '	do	',
		},
		{
			idCountry: 99,
			utc: '	UTC-4	',
			timeZone: '	America/Glace_Bay	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 100,
			utc: '	UTC-4	',
			timeZone: '	America/Goose_Bay	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 101,
			utc: '	UTC-4	',
			timeZone: '	America/Grenada	',
			country: '	Grenada	',
			flagCode: '	gd	',
		},
		{
			idCountry: 102,
			utc: '	UTC-4	',
			timeZone: '	America/Guadeloupe	',
			country: '	Guadeloupe	',
			flagCode: '	gp	',
		},
		{
			idCountry: 103,
			utc: '	UTC-4	',
			timeZone: '	America/Guyana	',
			country: '	Guyana	',
			flagCode: '	gy	',
		},
		{
			idCountry: 104,
			utc: '	UTC-4	',
			timeZone: '	America/Halifax	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 105,
			utc: '	UTC-4	',
			timeZone: '	America/La_Paz	',
			country: '	Bolivia	',
			flagCode: '	bo	',
		},
		{
			idCountry: 106,
			utc: '	UTC-4	',
			timeZone: '	America/Lower_Princes	',
			country: '	Sint Maarten	',
			flagCode: '	sx	',
		},
		{
			idCountry: 107,
			utc: '	UTC-4	',
			timeZone: '	America/Manaus	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 108,
			utc: '	UTC-4	',
			timeZone: '	America/Marigot	',
			country: '	Saint Martin	',
			flagCode: '	mf	',
		},
		{
			idCountry: 109,
			utc: '	UTC-4	',
			timeZone: '	America/Martinique	',
			country: '	Martinique	',
			flagCode: '	mq	',
		},
		{
			idCountry: 110,
			utc: '	UTC-4	',
			timeZone: '	America/Moncton	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 111,
			utc: '	UTC-4	',
			timeZone: '	America/Montserrat	',
			country: '	Montserrat	',
			flagCode: '	ms	',
		},
		{
			idCountry: 112,
			utc: '	UTC-4	',
			timeZone: '	America/Porto_Velho	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 113,
			utc: '	UTC-4	',
			timeZone: '	America/Port_of_Spain	',
			country: '	Trinidad and Tobago	',
			flagCode: '	tt	',
		},
		{
			idCountry: 114,
			utc: '	UTC-4	',
			timeZone: '	America/Puerto_Rico	',
			country: '	Puerto Rico	',
			flagCode: '	pr	',
		},
		{
			idCountry: 115,
			utc: '	UTC-4	',
			timeZone: '	America/Santiago	',
			country: '	Chile	',
			flagCode: '	cl	',
		},
		{
			idCountry: 116,
			utc: '	UTC-4	',
			timeZone: '	America/Santo_Domingo	',
			country: '	Dominican Republic	',
			flagCode: '	do	',
		},
		{
			idCountry: 117,
			utc: '	UTC-4	',
			timeZone: '	America/St_Barthelemy	',
			country: '	Saint Barthelemy	',
			flagCode: '	bl	',
		},
		{
			idCountry: 118,
			utc: '	UTC-4	',
			timeZone: '	America/St_Kitts	',
			country: '	Saint Kitts and Nevis	',
			flagCode: '	kn	',
		},
		{
			idCountry: 119,
			utc: '	UTC-4	',
			timeZone: '	America/St_Lucia	',
			country: '	Saint Lucia	',
			flagCode: '	lc	',
		},
		{
			idCountry: 120,
			utc: '	UTC-4	',
			timeZone: '	America/St_Thomas	',
			country: '	U.S. Virgin Islands	',
			flagCode: '	vi	',
		},
		{
			idCountry: 121,
			utc: '	UTC-4	',
			timeZone: '	America/St_Vincent	',
			country: '	Saint Vincent and the Grenadines	',
			flagCode: '	vc	',
		},
		{
			idCountry: 122,
			utc: '	UTC-4	',
			timeZone: '	America/Thule	',
			country: '	Greenland	',
			flagCode: '	gl	',
		},
		{
			idCountry: 123,
			utc: '	UTC-4	',
			timeZone: '	America/Tortola	',
			country: '	British Virgin Islands	',
			flagCode: '	vg	',
		},
		{
			idCountry: 124,
			utc: '	UTC-4	',
			timeZone: '	Atlantic/Bermuda	',
			country: '	Bermuda	',
			flagCode: '	bm	',
		},
		{
			idCountry: 125,
			utc: '	UTC-3:30	',
			timeZone: '	America/St_Johns	',
			country: '	Canada	',
			flagCode: '	ca	',
		},
		{
			idCountry: 126,
			utc: '	UTC-3	',
			timeZone: '	America/Araguaina	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 127,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Buenos_Aires	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 128,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Catamarca	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 129,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Cordoba	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 130,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Jujuy	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 131,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/La_Rioja	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 132,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Mendoza	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 133,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Rio_Gallegos	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 134,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Salta	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 135,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/San_Juan	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 136,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/San_Luis	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 137,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Tucuman	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 138,
			utc: '	UTC-3	',
			timeZone: '	America/Argentina/Ushuaia	',
			country: '	Argentina	',
			flagCode: '	ar	',
		},
		{
			idCountry: 139,
			utc: '	UTC-3	',
			timeZone: '	America/Bahia	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 140,
			utc: '	UTC-3	',
			timeZone: '	America/Belem	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 141,
			utc: '	UTC-3	',
			timeZone: '	America/Cayenne	',
			country: '	French Guiana	',
			flagCode: '	gf	',
		},
		{
			idCountry: 142,
			utc: '	UTC-3	',
			timeZone: '	America/Fortaleza	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 143,
			utc: '	UTC-3	',
			timeZone: '	America/Maceio	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 144,
			utc: '	UTC-3	',
			timeZone: '	America/Miquelon	',
			country: '	Saint Pierre and Miquelon	',
			flagCode: '	pm	',
		},
		{
			idCountry: 145,
			utc: '	UTC-3	',
			timeZone: '	America/Montevideo	',
			country: '	Uruguay	',
			flagCode: '	uy	',
		},
		{
			idCountry: 146,
			utc: '	UTC-3	',
			timeZone: '	America/Nuuk	',
			country: '	Greenland	',
			flagCode: '	gl	',
		},
		{
			idCountry: 147,
			utc: '	UTC-3	',
			timeZone: '	America/Paramaribo	',
			country: '	Suriname	',
			flagCode: '	sr	',
		},
		{
			idCountry: 148,
			utc: '	UTC-3	',
			timeZone: '	America/Punta_Arenas	',
			country: '	Chile	',
			flagCode: '	cl	',
		},
		{
			idCountry: 149,
			utc: '	UTC-3	',
			timeZone: '	America/Recife	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 150,
			utc: '	UTC-3	',
			timeZone: '	America/Santarem	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 151,
			utc: '	UTC-3	',
			timeZone: '	America/Sao_Paulo	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 152,
			utc: '	UTC-3	',
			timeZone: '	Antarctica/Palmer	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 153,
			utc: '	UTC-3	',
			timeZone: '	Antarctica/Rothera	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 154,
			utc: '	UTC-3	',
			timeZone: '	Atlantic/Stanley	',
			country: '	Falkland Islands	',
			flagCode: '	fk	',
		},
		{
			idCountry: 155,
			utc: '	UTC-2	',
			timeZone: '	America/Noronha	',
			country: '	Brazil	',
			flagCode: '	br	',
		},
		{
			idCountry: 156,
			utc: '	UTC-2	',
			timeZone: '	Atlantic/South_Georgia	',
			country:
				'	South Georgia and the South Sandwich Islands	',
			flagCode: '	gs	',
		},
		{
			idCountry: 157,
			utc: '	UTC-1	',
			timeZone: '	America/Scoresbysund	',
			country: '	Greenland	',
			flagCode: '	gl	',
		},
		{
			idCountry: 158,
			utc: '	UTC-1	',
			timeZone: '	Atlantic/Azores	',
			country: '	Portugal	',
			flagCode: '	pt	',
		},
		{
			idCountry: 159,
			utc: '	UTC-1	',
			timeZone: '	Atlantic/Cape_Verde	',
			country: '	Cabo Verde	',
			flagCode: '	cv	',
		},
		{
			idCountry: 160,
			utc: '	UTC+0	',
			timeZone: '	Africa/Abidjan	',
			country: '	Ivory Coast	',
			flagCode: '	ci	',
		},
		{
			idCountry: 161,
			utc: '	UTC+0	',
			timeZone: '	Africa/Accra	',
			country: '	Ghana	',
			flagCode: '	gh	',
		},
		{
			idCountry: 162,
			utc: '	UTC+0	',
			timeZone: '	Africa/Bamako	',
			country: '	Mali	',
			flagCode: '	ml	',
		},
		{
			idCountry: 163,
			utc: '	UTC+0	',
			timeZone: '	Africa/Banjul	',
			country: '	Gambia	',
			flagCode: '	gm	',
		},
		{
			idCountry: 164,
			utc: '	UTC+0	',
			timeZone: '	Africa/Bissau	',
			country: '	Guinea-Bissau	',
			flagCode: '	gw	',
		},
		{
			idCountry: 165,
			utc: '	UTC+0	',
			timeZone: '	Africa/Casablanca	',
			country: '	Morocco	',
			flagCode: '	ma	',
		},
		{
			idCountry: 166,
			utc: '	UTC+0	',
			timeZone: '	Africa/Conakry	',
			country: '	Guinea	',
			flagCode: '	gn	',
		},
		{
			idCountry: 167,
			utc: '	UTC+0	',
			timeZone: '	Africa/Dakar	',
			country: '	Senegal	',
			flagCode: '	sn	',
		},
		{
			idCountry: 168,
			utc: '	UTC+0	',
			timeZone: '	Africa/El_Aaiun	',
			country: '	Western Sahara	',
			flagCode: '	eh	',
		},
		{
			idCountry: 169,
			utc: '	UTC+0	',
			timeZone: '	Africa/Freetown	',
			country: '	Sierra Leone	',
			flagCode: '	sl	',
		},
		{
			idCountry: 170,
			utc: '	UTC+0	',
			timeZone: '	Africa/Lome	',
			country: '	Togo	',
			flagCode: '	tg	',
		},
		{
			idCountry: 171,
			utc: '	UTC+0	',
			timeZone: '	Africa/Monrovia	',
			country: '	Liberia	',
			flagCode: '	lr	',
		},
		{
			idCountry: 172,
			utc: '	UTC+0	',
			timeZone: '	Africa/Nouakchott	',
			country: '	Mauritania	',
			flagCode: '	mr	',
		},
		{
			idCountry: 173,
			utc: '	UTC+0	',
			timeZone: '	Africa/Ouagadougou	',
			country: '	Burkina Faso	',
			flagCode: '	bf	',
		},
		{
			idCountry: 174,
			utc: '	UTC+0	',
			timeZone: '	Africa/Sao_Tome	',
			country: '	Sao Tome and Principe	',
			flagCode: '	st	',
		},
		{
			idCountry: 175,
			utc: '	UTC+0	',
			timeZone: '	America/Danmarkshavn	',
			country: '	Greenland	',
			flagCode: '	gl	',
		},
		{
			idCountry: 176,
			utc: '	UTC+0	',
			timeZone: '	Antarctica/Troll	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 177,
			utc: '	UTC+0	',
			timeZone: '	Atlantic/Canary	',
			country: '	Spain	',
			flagCode: '	es	',
		},
		{
			idCountry: 178,
			utc: '	UTC+0	',
			timeZone: '	Atlantic/Faroe	',
			country: '	Faroe Islands	',
			flagCode: '	fo	',
		},
		{
			idCountry: 179,
			utc: '	UTC+0	',
			timeZone: '	Atlantic/Madeira	',
			country: '	Portugal	',
			flagCode: '	pt	',
		},
		{
			idCountry: 180,
			utc: '	UTC+0	',
			timeZone: '	Atlantic/Reykjavik	',
			country: '	Iceland	',
			flagCode: '	is	',
		},
		{
			idCountry: 181,
			utc: '	UTC+0	',
			timeZone: '	Atlantic/St_Helena	',
			country: '	Saint Helena	',
			flagCode: '	sh	',
		},
		{
			idCountry: 182,
			utc: '	UTC+0	',
			timeZone: '	Europe/Dublin	',
			country: '	Ireland	',
			flagCode: '	ie	',
		},
		{
			idCountry: 183,
			utc: '	UTC+0	',
			timeZone: '	Europe/Guernsey	',
			country: '	Guernsey	',
			flagCode: '	gg	',
		},
		{
			idCountry: 184,
			utc: '	UTC+0	',
			timeZone: '	Europe/Isle_of_Man	',
			country: '	Isle of Man	',
			flagCode: '	mi	',
		},
		{
			idCountry: 185,
			utc: '	UTC+0	',
			timeZone: '	Europe/Jersey	',
			country: '	Jersey	',
			flagCode: '	je	',
		},
		{
			idCountry: 186,
			utc: '	UTC+0	',
			timeZone: '	Europe/Lisbon	',
			country: '	Portugal	',
			flagCode: '	pt	',
		},
		{
			idCountry: 187,
			utc: '	UTC+0	',
			timeZone: '	Europe/London	',
			country: '	United Kingdom	',
			flagCode: '	gb	',
		},
		{
			idCountry: 188,
			utc: '	UTC+1	',
			timeZone: '	Africa/Algiers	',
			country: '	Algeria	',
			flagCode: '	dz	',
		},
		{
			idCountry: 189,
			utc: '	UTC+1	',
			timeZone: '	Africa/Bangui	',
			country: '	Central African Republic	',
			flagCode: '	cf	',
		},
		{
			idCountry: 190,
			utc: '	UTC+1	',
			timeZone: '	Africa/Brazzaville	',
			country: '	Republic of the Congo	',
			flagCode: '	cg	',
		},
		{
			idCountry: 191,
			utc: '	UTC+1	',
			timeZone: '	Africa/Ceuta	',
			country: '	Spain	',
			flagCode: '	es	',
		},
		{
			idCountry: 192,
			utc: '	UTC+1	',
			timeZone: '	Africa/Douala	',
			country: '	Cameroon	',
			flagCode: '	cm	',
		},
		{
			idCountry: 193,
			utc: '	UTC+1	',
			timeZone: '	Africa/Kinshasa	',
			country: '	Democratic Republic of the Congo	',
			flagCode: '	cd	',
		},
		{
			idCountry: 194,
			utc: '	UTC+1	',
			timeZone: '	Africa/Lagos	',
			country: '	Nigeria	',
			flagCode: '	ng	',
		},
		{
			idCountry: 195,
			utc: '	UTC+1	',
			timeZone: '	Africa/Libreville	',
			country: '	Gabon	',
			flagCode: '	ga	',
		},
		{
			idCountry: 196,
			utc: '	UTC+1	',
			timeZone: '	Africa/Luanda	',
			country: '	Angola	',
			flagCode: '	ao	',
		},
		{
			idCountry: 197,
			utc: '	UTC+1	',
			timeZone: '	Africa/Malabo	',
			country: '	Equatorial Guinea	',
			flagCode: '	gq	',
		},
		{
			idCountry: 198,
			utc: '	UTC+1	',
			timeZone: '	Africa/Ndjamena	',
			country: '	Chad	',
			flagCode: '	td	',
		},
		{
			idCountry: 199,
			utc: '	UTC+1	',
			timeZone: '	Africa/Porto-Novo	',
			country: '	Benin	',
			flagCode: '	bj	',
		},
		{
			idCountry: 200,
			utc: '	UTC+1	',
			timeZone: '	Africa/Tunis	',
			country: '	Tunisia	',
			flagCode: '	tn	',
		},
		{
			idCountry: 201,
			utc: '	UTC+1	',
			timeZone: '	Africa/Windhoek	',
			country: '	Namibia	',
			flagCode: '	na	',
		},
		{
			idCountry: 202,
			utc: '	UTC+1	',
			timeZone: '	Europe/Amsterdam	',
			country: '	Netherlands	',
			flagCode: '	nl	',
		},
		{
			idCountry: 203,
			utc: '	UTC+1	',
			timeZone: '	Europe/Andorra	',
			country: '	Andorra	',
			flagCode: '	ad	',
		},
		{
			idCountry: 204,
			utc: '	UTC+1	',
			timeZone: '	Europe/Belgrade	',
			country: '	Serbia	',
			flagCode: '	rs	',
		},
		{
			idCountry: 205,
			utc: '	UTC+1	',
			timeZone: '	Europe/Berlin	',
			country: '	Germany	',
			flagCode: '	de	',
		},
		{
			idCountry: 206,
			utc: '	UTC+1	',
			timeZone: '	Europe/Bratislava	',
			country: '	Slovakia	',
			flagCode: '	sk	',
		},
		{
			idCountry: 207,
			utc: '	UTC+1	',
			timeZone: '	Europe/Brussels	',
			country: '	Belgium	',
			flagCode: '	be	',
		},
		{
			idCountry: 208,
			utc: '	UTC+1	',
			timeZone: '	Europe/Budapest	',
			country: '	Hungary	',
			flagCode: '	hu	',
		},
		{
			idCountry: 209,
			utc: '	UTC+1	',
			timeZone: '	Europe/Busingen	',
			country: '	Germany	',
			flagCode: '	de	',
		},
		{
			idCountry: 210,
			utc: '	UTC+1	',
			timeZone: '	Europe/Copenhagen	',
			country: '	Denmark	',
			flagCode: '	dk	',
		},
		{
			idCountry: 211,
			utc: '	UTC+1	',
			timeZone: '	Europe/Gibraltar	',
			country: '	Gibraltar	',
			flagCode: '	gi	',
		},
		{
			idCountry: 212,
			utc: '	UTC+1	',
			timeZone: '	Europe/Ljubljana	',
			country: '	Slovenia	',
			flagCode: '	si	',
		},
		{
			idCountry: 213,
			utc: '	UTC+1	',
			timeZone: '	Europe/Luxembourg	',
			country: '	Luxembourg	',
			flagCode: '	lu	',
		},
		{
			idCountry: 214,
			utc: '	UTC+1	',
			timeZone: '	Europe/Madrid	',
			country: '	Spain	',
			flagCode: '	es	',
		},
		{
			idCountry: 215,
			utc: '	UTC+1	',
			timeZone: '	Europe/Malta	',
			country: '	Malta	',
			flagCode: '	mt	',
		},
		{
			idCountry: 216,
			utc: '	UTC+1	',
			timeZone: '	Europe/Monaco	',
			country: '	Monaco	',
			flagCode: '	mc	',
		},
		{
			idCountry: 217,
			utc: '	UTC+1	',
			timeZone: '	Europe/Oslo	',
			country: '	Norway	',
			flagCode: '	no	',
		},
		{
			idCountry: 218,
			utc: '	UTC+1	',
			timeZone: '	Europe/Paris	',
			country: '	France	',
			flagCode: '	fr	',
		},
		{
			idCountry: 219,
			utc: '	UTC+1	',
			timeZone: '	Europe/Podgorica	',
			country: '	Montenegro	',
			flagCode: '	me	',
		},
		{
			idCountry: 220,
			utc: '	UTC+1	',
			timeZone: '	Europe/Prague	',
			country: '	Czechia	',
			flagCode: '	cz	',
		},
		{
			idCountry: 221,
			utc: '	UTC+1	',
			timeZone: '	Europe/Rome	',
			country: '	Italy	',
			flagCode: '	it	',
		},
		{
			idCountry: 222,
			utc: '	UTC+1	',
			timeZone: '	Europe/San_Marino	',
			country: '	San Marino	',
			flagCode: '	sm	',
		},
		{
			idCountry: 223,
			utc: '	UTC+1	',
			timeZone: '	Europe/Sarajevo	',
			country: '	Bosnia and Herzegovina	',
			flagCode: '	ba	',
		},
		{
			idCountry: 224,
			utc: '	UTC+1	',
			timeZone: '	Europe/Skopje	',
			country: '	North Macedonia	',
			flagCode: '	mk	',
		},
		{
			idCountry: 225,
			utc: '	UTC+1	',
			timeZone: '	Europe/Stockholm	',
			country: '	Sweden	',
			flagCode: '	se	',
		},
		{
			idCountry: 226,
			utc: '	UTC+1	',
			timeZone: '	Europe/Tirane	',
			country: '	Albania	',
			flagCode: '	al	',
		},
		{
			idCountry: 227,
			utc: '	UTC+1	',
			timeZone: '	Europe/Vaduz	',
			country: '	Liechtenstein	',
			flagCode: '	li	',
		},
		{
			idCountry: 228,
			utc: '	UTC+1	',
			timeZone: '	Europe/Vatican	',
			country: '	Vatican	',
			flagCode: '	va	',
		},
		{
			idCountry: 229,
			utc: '	UTC+1	',
			timeZone: '	Europe/Vienna	',
			country: '	Austria	',
			flagCode: '	au	',
		},
		{
			idCountry: 230,
			utc: '	UTC+1	',
			timeZone: '	Europe/Warsaw	',
			country: '	Poland	',
			flagCode: '	pl	',
		},
		{
			idCountry: 231,
			utc: '	UTC+1	',
			timeZone: '	Europe/Zagreb	',
			country: '	Croatia	',
			flagCode: '	hr	',
		},
		{
			idCountry: 232,
			utc: '	UTC+1	',
			timeZone: '	Europe/Zurich	',
			country: '	Switzerland	',
			flagCode: '	ch	',
		},
		{
			idCountry: 233,
			utc: '	UTC+2	',
			timeZone: '	Africa/Blantyre	',
			country: '	Malawi	',
			flagCode: '	mw	',
		},
		{
			idCountry: 234,
			utc: '	UTC+2	',
			timeZone: '	Africa/Bujumbura	',
			country: '	Burundi	',
			flagCode: '	bi	',
		},
		{
			idCountry: 235,
			utc: '	UTC+2	',
			timeZone: '	Africa/Cairo	',
			country: '	Egypt	',
			flagCode: '	eg	',
		},
		{
			idCountry: 236,
			utc: '	UTC+2	',
			timeZone: '	Africa/Gaborone	',
			country: '	Botswana	',
			flagCode: '	bw	',
		},
		{
			idCountry: 237,
			utc: '	UTC+2	',
			timeZone: '	Africa/Harare	',
			country: '	Zimbabwe	',
			flagCode: '	zw	',
		},
		{
			idCountry: 238,
			utc: '	UTC+2	',
			timeZone: '	Africa/Johannesburg	',
			country: '	South Africa	',
			flagCode: '	za	',
		},
		{
			idCountry: 239,
			utc: '	UTC+2	',
			timeZone: '	Africa/Juba	',
			country: '	South Sudan	',
			flagCode: '	ss	',
		},
		{
			idCountry: 240,
			utc: '	UTC+2	',
			timeZone: '	Africa/Khartoum	',
			country: '	Sudan	',
			flagCode: '	sd	',
		},
		{
			idCountry: 241,
			utc: '	UTC+2	',
			timeZone: '	Africa/Kigali	',
			country: '	Rwanda	',
			flagCode: '	rw	',
		},
		{
			idCountry: 242,
			utc: '	UTC+2	',
			timeZone: '	Africa/Lubumbashi	',
			country: '	Democratic Republic of the Congo	',
			flagCode: '	cd	',
		},
		{
			idCountry: 243,
			utc: '	UTC+2	',
			timeZone: '	Africa/Lusaka	',
			country: '	Zambia	',
			flagCode: '	zm	',
		},
		{
			idCountry: 244,
			utc: '	UTC+2	',
			timeZone: '	Africa/Maputo	',
			country: '	Mozambique	',
			flagCode: '	mz	',
		},
		{
			idCountry: 245,
			utc: '	UTC+2	',
			timeZone: '	Africa/Maseru	',
			country: '	Lesotho	',
			flagCode: '	ls	',
		},
		{
			idCountry: 246,
			utc: '	UTC+2	',
			timeZone: '	Africa/Mbabane	',
			country: '	Eswatini	',
			flagCode: '	sz	',
		},
		{
			idCountry: 247,
			utc: '	UTC+2	',
			timeZone: '	Africa/Tripoli	',
			country: '	Libya	',
			flagCode: '	ly	',
		},
		{
			idCountry: 248,
			utc: '	UTC+2	',
			timeZone: '	Asia/Beirut	',
			country: '	Lebanon	',
			flagCode: '	lb	',
		},
		{
			idCountry: 249,
			utc: '	UTC+2	',
			timeZone: '	Asia/Famagusta	',
			country: '	Cyprus	',
			flagCode: '	cy	',
		},
		{
			idCountry: 250,
			utc: '	UTC+2	',
			timeZone: '	Asia/Jerusalem	',
			country: '	Israel	',
			flagCode: '	il	',
		},
		{
			idCountry: 251,
			utc: '	UTC+2	',
			timeZone: '	Asia/Nicosia	',
			country: '	Cyprus	',
			flagCode: '	cy	',
		},
		{
			idCountry: 252,
			utc: '	UTC+2	',
			timeZone: '	Europe/Athens	',
			country: '	Greece	',
			flagCode: '	gr	',
		},
		{
			idCountry: 253,
			utc: '	UTC+2	',
			timeZone: '	Europe/Bucharest	',
			country: '	Romania	',
			flagCode: '	ro	',
		},
		{
			idCountry: 254,
			utc: '	UTC+2	',
			timeZone: '	Europe/Chisinau	',
			country: '	Moldova	',
			flagCode: '	md	',
		},
		{
			idCountry: 255,
			utc: '	UTC+2	',
			timeZone: '	Europe/Helsinki	',
			country: '	Finland	',
			flagCode: '	fi	',
		},
		{
			idCountry: 256,
			utc: '	UTC+2	',
			timeZone: '	Europe/Kaliningrad	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 257,
			utc: '	UTC+2	',
			timeZone: '	Europe/Kyiv	',
			country: '	Ukraine	',
			flagCode: '	ua	',
		},
		{
			idCountry: 258,
			utc: '	UTC+2	',
			timeZone: '	Europe/Mariehamn	',
			country: '	Aland Islands	',
			flagCode: '	ax	',
		},
		{
			idCountry: 259,
			utc: '	UTC+2	',
			timeZone: '	Europe/Riga	',
			country: '	Latvia	',
			flagCode: '	lv	',
		},
		{
			idCountry: 260,
			utc: '	UTC+2	',
			timeZone: '	Europe/Sofia	',
			country: '	Bulgaria	',
			flagCode: '	bg	',
		},
		{
			idCountry: 261,
			utc: '	UTC+2	',
			timeZone: '	Europe/Tallinn	',
			country: '	Estonia	',
			flagCode: '	ee	',
		},
		{
			idCountry: 262,
			utc: '	UTC+2	',
			timeZone: '	Europe/Vilnius	',
			country: '	Lithuania	',
			flagCode: '	lt	',
		},
		{
			idCountry: 263,
			utc: '	UTC+3	',
			timeZone: '	Africa/Addis_Ababa	',
			country: '	Ethiopia	',
			flagCode: '	et	',
		},
		{
			idCountry: 264,
			utc: '	UTC+3	',
			timeZone: '	Africa/Asmara	',
			country: '	Eritrea	',
			flagCode: '	er	',
		},
		{
			idCountry: 265,
			utc: '	UTC+3	',
			timeZone: '	Africa/Dar_es_Salaam	',
			country: '	Tanzania	',
			flagCode: '	tz	',
		},
		{
			idCountry: 266,
			utc: '	UTC+3	',
			timeZone: '	Africa/Djibouti	',
			country: '	Djibouti	',
			flagCode: '	dj	',
		},
		{
			idCountry: 267,
			utc: '	UTC+3	',
			timeZone: '	Africa/Kampala	',
			country: '	Uganda	',
			flagCode: '	ug	',
		},
		{
			idCountry: 268,
			utc: '	UTC+3	',
			timeZone: '	Africa/Mogadishu	',
			country: '	Somalia	',
			flagCode: '	so	',
		},
		{
			idCountry: 269,
			utc: '	UTC+3	',
			timeZone: '	Africa/Nairobi	',
			country: '	Kenya	',
			flagCode: '	ke	',
		},
		{
			idCountry: 270,
			utc: '	UTC+3	',
			timeZone: '	Antarctica/Syowa	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 271,
			utc: '	UTC+3	',
			timeZone: '	Asia/Aden	',
			country: '	Yemen	',
			flagCode: '	ye	',
		},
		{
			idCountry: 272,
			utc: '	UTC+3	',
			timeZone: '	Asia/Amman	',
			country: '	Jordan	',
			flagCode: '	jo	',
		},
		{
			idCountry: 273,
			utc: '	UTC+3	',
			timeZone: '	Asia/Baghdad	',
			country: '	Iraq	',
			flagCode: '	iq	',
		},
		{
			idCountry: 274,
			utc: '	UTC+3	',
			timeZone: '	Asia/Bahrain	',
			country: '	Bahrain	',
			flagCode: '	bh	',
		},
		{
			idCountry: 275,
			utc: '	UTC+3	',
			timeZone: '	Asia/Damascus	',
			country: '	Syria	',
			flagCode: '	sy	',
		},
		{
			idCountry: 276,
			utc: '	UTC+3	',
			timeZone: '	Asia/Kuwait	',
			country: '	Kuwait	',
			flagCode: '	kw	',
		},
		{
			idCountry: 277,
			utc: '	UTC+3	',
			timeZone: '	Asia/Qatar	',
			country: '	Qatar	',
			flagCode: '	qa	',
		},
		{
			idCountry: 278,
			utc: '	UTC+3	',
			timeZone: '	Asia/Riyadh	',
			country: '	Saudi Arabia	',
			flagCode: '	sa	',
		},
		{
			idCountry: 279,
			utc: '	UTC+3	',
			timeZone: '	Europe/Istanbul	',
			country: '	Turkey	',
			flagCode: '	tr	',
		},
		{
			idCountry: 280,
			utc: '	UTC+3	',
			timeZone: '	Europe/Kirov	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 281,
			utc: '	UTC+3	',
			timeZone: '	Europe/Minsk	',
			country: '	Belarus	',
			flagCode: '	by	',
		},
		{
			idCountry: 282,
			utc: '	UTC+3	',
			timeZone: '	Europe/Moscow	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 283,
			utc: '	UTC+3	',
			timeZone: '	Europe/Simferopol	',
			country: '	Ukraine	',
			flagCode: '	ua	',
		},
		{
			idCountry: 284,
			utc: '	UTC+3	',
			timeZone: '	Europe/Volgograd	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 285,
			utc: '	UTC+3	',
			timeZone: '	Indian/Antananarivo	',
			country: '	Madagascar	',
			flagCode: '	mg	',
		},
		{
			idCountry: 286,
			utc: '	UTC+3	',
			timeZone: '	Indian/Comoro	',
			country: '	Comoros	',
			flagCode: '	km	',
		},
		{
			idCountry: 287,
			utc: '	UTC+3	',
			timeZone: '	Indian/Mayotte	',
			country: '	Mayotte	',
			flagCode: '	yt	',
		},
		{
			idCountry: 288,
			utc: '	UTC+3:30	',
			timeZone: '	Asia/Tehran	',
			country: '	Iran	',
			flagCode: '	ir	',
		},
		{
			idCountry: 289,
			utc: '	UTC+4	',
			timeZone: '	Asia/Baku	',
			country: '	Azerbaijan	',
			flagCode: '	az	',
		},
		{
			idCountry: 290,
			utc: '	UTC+4	',
			timeZone: '	Asia/Dubai	',
			country: '	United Arab Emirates	',
			flagCode: '	ae	',
		},
		{
			idCountry: 291,
			utc: '	UTC+4	',
			timeZone: '	Asia/Muscat	',
			country: '	Oman	',
			flagCode: '	om	',
		},
		{
			idCountry: 292,
			utc: '	UTC+4	',
			timeZone: '	Asia/Tbilisi	',
			country: '	Georgia	',
			flagCode: '	ge	',
		},
		{
			idCountry: 293,
			utc: '	UTC+4	',
			timeZone: '	Asia/Yerevan	',
			country: '	Armenia	',
			flagCode: '	am	',
		},
		{
			idCountry: 294,
			utc: '	UTC+4	',
			timeZone: '	Europe/Astrakhan	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 295,
			utc: '	UTC+4	',
			timeZone: '	Europe/Samara	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 296,
			utc: '	UTC+4	',
			timeZone: '	Europe/Saratov	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 297,
			utc: '	UTC+4	',
			timeZone: '	Europe/Ulyanovsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 298,
			utc: '	UTC+4	',
			timeZone: '	Indian/Mahe	',
			country: '	Seychelles	',
			flagCode: '	sc	',
		},
		{
			idCountry: 299,
			utc: '	UTC+4	',
			timeZone: '	Indian/Mauritius	',
			country: '	Mauritius	',
			flagCode: '	mu	',
		},
		{
			idCountry: 300,
			utc: '	UTC+4	',
			timeZone: '	Indian/Reunion	',
			country: '	Reunion	',
			flagCode: '	re	',
		},
		{
			idCountry: 301,
			utc: '	UTC+4:30	',
			timeZone: '	Asia/Kabul	',
			country: '	Afghanistan	',
			flagCode: '	af	',
		},
		{
			idCountry: 302,
			utc: '	UTC+5	',
			timeZone: '	Antarctica/Mawson	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 303,
			utc: '	UTC+5	',
			timeZone: '	Asia/Aqtau	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 304,
			utc: '	UTC+5	',
			timeZone: '	Asia/Aqtobe	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 305,
			utc: '	UTC+5	',
			timeZone: '	Asia/Ashgabat	',
			country: '	Turkmenistan	',
			flagCode: '	tm	',
		},
		{
			idCountry: 306,
			utc: '	UTC+5	',
			timeZone: '	Asia/Atyrau	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 307,
			utc: '	UTC+5	',
			timeZone: '	Asia/Dushanbe	',
			country: '	Tajikistan	',
			flagCode: '	tj	',
		},
		{
			idCountry: 308,
			utc: '	UTC+5	',
			timeZone: '	Asia/Karachi	',
			country: '	Pakistan	',
			flagCode: '	pk	',
		},
		{
			idCountry: 309,
			utc: '	UTC+5	',
			timeZone: '	Asia/Oral	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 310,
			utc: '	UTC+5	',
			timeZone: '	Asia/Qyzylorda	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 311,
			utc: '	UTC+5	',
			timeZone: '	Asia/Samarkand	',
			country: '	Uzbekistan	',
			flagCode: '	uz	',
		},
		{
			idCountry: 312,
			utc: '	UTC+5	',
			timeZone: '	Asia/Tashkent	',
			country: '	Uzbekistan	',
			flagCode: '	uz	',
		},
		{
			idCountry: 313,
			utc: '	UTC+5	',
			timeZone: '	Asia/Yekaterinburg	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 314,
			utc: '	UTC+5	',
			timeZone: '	Indian/Kerguelen	',
			country: '	French Southern Territories	',
			flagCode: '	tf	',
		},
		{
			idCountry: 315,
			utc: '	UTC+5	',
			timeZone: '	Indian/Maldives	',
			country: '	Maldives	',
			flagCode: '	mv	',
		},
		{
			idCountry: 316,
			utc: '	UTC+5:30	',
			timeZone: '	Asia/Colombo	',
			country: '	Sri Lanka	',
			flagCode: '	lk	',
		},
		{
			idCountry: 317,
			utc: '	UTC+5:30	',
			timeZone: '	Asia/Kolkata	',
			country: '	India	',
			flagCode: '	in	',
		},
		{
			idCountry: 318,
			utc: '	UTC+5:45	',
			timeZone: '	Asia/Kathmandu	',
			country: '	Nepal	',
			flagCode: '	np	',
		},
		{
			idCountry: 319,
			utc: '	UTC+6	',
			timeZone: '	Antarctica/Vostok	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 320,
			utc: '	UTC+6	',
			timeZone: '	Asia/Almaty	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 321,
			utc: '	UTC+6	',
			timeZone: '	Asia/Bishkek	',
			country: '	Kyrgyzstan	',
			flagCode: '	kg	',
		},
		{
			idCountry: 322,
			utc: '	UTC+6	',
			timeZone: '	Asia/Dhaka	',
			country: '	Bangladesh	',
			flagCode: '	bd	',
		},
		{
			idCountry: 323,
			utc: '	UTC+6	',
			timeZone: '	Asia/Omsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 324,
			utc: '	UTC+6	',
			timeZone: '	Asia/Qostanay	',
			country: '	Kazakhstan	',
			flagCode: '	kz	',
		},
		{
			idCountry: 325,
			utc: '	UTC+6	',
			timeZone: '	Asia/Thimphu	',
			country: '	Bhutan	',
			flagCode: '	bt	',
		},
		{
			idCountry: 326,
			utc: '	UTC+6	',
			timeZone: '	Asia/Urumqi	',
			country: '	China	',
			flagCode: '	cn	',
		},
		{
			idCountry: 327,
			utc: '	UTC+6	',
			timeZone: '	Indian/Chagos	',
			country: '	British Indian Ocean Territory	',
			flagCode: '	io	',
		},
		{
			idCountry: 328,
			utc: '	UTC+6:30	',
			timeZone: '	Asia/Yangon	',
			country: '	Myanmar	',
			flagCode: '	mm	',
		},
		{
			idCountry: 329,
			utc: '	UTC+6:30	',
			timeZone: '	Indian/Cocos	',
			country: '	Cocos Islands	',
			flagCode: '	cc	',
		},
		{
			idCountry: 330,
			utc: '	UTC+7	',
			timeZone: '	Antarctica/Davis	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 331,
			utc: '	UTC+7	',
			timeZone: '	Asia/Bangkok	',
			country: '	Thailand	',
			flagCode: '	th	',
		},
		{
			idCountry: 332,
			utc: '	UTC+7	',
			timeZone: '	Asia/Barnaul	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 333,
			utc: '	UTC+7	',
			timeZone: '	Asia/Hovd	',
			country: '	Mongolia	',
			flagCode: '	mn	',
		},
		{
			idCountry: 334,
			utc: '	UTC+7	',
			timeZone: '	Asia/Ho_Chi_Minh	',
			country: '	Vietnam	',
			flagCode: '	vn	',
		},
		{
			idCountry: 335,
			utc: '	UTC+7	',
			timeZone: '	Asia/Jakarta	',
			country: '	Indonesia	',
			flagCode: '	id	',
		},
		{
			idCountry: 336,
			utc: '	UTC+7	',
			timeZone: '	Asia/Krasnoyarsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 337,
			utc: '	UTC+7	',
			timeZone: '	Asia/Novokuznetsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 338,
			utc: '	UTC+7	',
			timeZone: '	Asia/Novosibirsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 339,
			utc: '	UTC+7	',
			timeZone: '	Asia/Phnom_Penh	',
			country: '	Cambodia	',
			flagCode: '	kh	',
		},
		{
			idCountry: 340,
			utc: '	UTC+7	',
			timeZone: '	Asia/Pontianak	',
			country: '	Indonesia	',
			flagCode: '	id	',
		},
		{
			idCountry: 341,
			utc: '	UTC+7	',
			timeZone: '	Asia/Tomsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 342,
			utc: '	UTC+7	',
			timeZone: '	Asia/Vientiane	',
			country: '	Laos	',
			flagCode: '	la	',
		},
		{
			idCountry: 343,
			utc: '	UTC+7	',
			timeZone: '	Indian/Christmas	',
			country: '	Christmas Island	',
			flagCode: '	cx	',
		},
		{
			idCountry: 344,
			utc: '	UTC+8	',
			timeZone: '	Asia/Brunei	',
			country: '	Brunei	',
			flagCode: '	bn	',
		},
		{
			idCountry: 345,
			utc: '	UTC+8	',
			timeZone: '	Asia/Choibalsan	',
			country: '	Mongolia	',
			flagCode: '	mn	',
		},
		{
			idCountry: 346,
			utc: '	UTC+8	',
			timeZone: '	Asia/Hong_Kong	',
			country: '	Hong Kong	',
			flagCode: '	hk	',
		},
		{
			idCountry: 347,
			utc: '	UTC+8	',
			timeZone: '	Asia/Irkutsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 348,
			utc: '	UTC+8	',
			timeZone: '	Asia/Kuala_Lumpur	',
			country: '	Malaysia	',
			flagCode: '	my	',
		},
		{
			idCountry: 349,
			utc: '	UTC+8	',
			timeZone: '	Asia/Kuching	',
			country: '	Malaysia	',
			flagCode: '	my	',
		},
		{
			idCountry: 350,
			utc: '	UTC+8	',
			timeZone: '	Asia/Macau	',
			country: '	Macao	',
			flagCode: '	mo	',
		},
		{
			idCountry: 351,
			utc: '	UTC+8	',
			timeZone: '	Asia/Makassar	',
			country: '	Indonesia	',
			flagCode: '	id	',
		},
		{
			idCountry: 352,
			utc: '	UTC+8	',
			timeZone: '	Asia/Manila	',
			country: '	Philippines	',
			flagCode: '	ph	',
		},
		{
			idCountry: 353,
			utc: '	UTC+8	',
			timeZone: '	Asia/Shanghai	',
			country: '	China	',
			flagCode: '	cn	',
		},
		{
			idCountry: 354,
			utc: '	UTC+8	',
			timeZone: '	Asia/Singapore	',
			country: '	Singapore	',
			flagCode: '	sg	',
		},
		{
			idCountry: 355,
			utc: '	UTC+8	',
			timeZone: '	Asia/Taipei	',
			country: '	Taiwan	',
			flagCode: '	tw	',
		},
		{
			idCountry: 356,
			utc: '	UTC+8	',
			timeZone: '	Asia/Ulaanbaatar	',
			country: '	Mongolia	',
			flagCode: '	mn	',
		},
		{
			idCountry: 357,
			utc: '	UTC+8	',
			timeZone: '	Australia/Perth	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 358,
			utc: '	UTC+8:45	',
			timeZone: '	Australia/Eucla	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 359,
			utc: '	UTC+9	',
			timeZone: '	Asia/Chita	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 360,
			utc: '	UTC+9	',
			timeZone: '	Asia/Dili	',
			country: '	Timor Leste	',
			flagCode: '	tl	',
		},
		{
			idCountry: 361,
			utc: '	UTC+9	',
			timeZone: '	Asia/Jayapura	',
			country: '	Indonesia	',
			flagCode: '	id	',
		},
		{
			idCountry: 362,
			utc: '	UTC+9	',
			timeZone: '	Asia/Khandyga	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 363,
			utc: '	UTC+9	',
			timeZone: '	Asia/Pyongyang	',
			country: '	North Korea	',
			flagCode: '	kp	',
		},
		{
			idCountry: 364,
			utc: '	UTC+9	',
			timeZone: '	Asia/Seoul	',
			country: '	South Korea	',
			flagCode: '	kr	',
		},
		{
			idCountry: 365,
			utc: '	UTC+9	',
			timeZone: '	Asia/Tokyo	',
			country: '	Japan	',
			flagCode: '	jp	',
		},
		{
			idCountry: 366,
			utc: '	UTC+9	',
			timeZone: '	Asia/Yakutsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 367,
			utc: '	UTC+9	',
			timeZone: '	Pacific/Palau	',
			country: '	Palau	',
			flagCode: '	pw	',
		},
		{
			idCountry: 368,
			utc: '	UTC+9:30	',
			timeZone: '	Australia/Adelaide	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 369,
			utc: '	UTC+9:30	',
			timeZone: '	Australia/Broken_Hill	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 370,
			utc: '	UTC+9:30	',
			timeZone: '	Australia/Darwin	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 371,
			utc: '	UTC+10	',
			timeZone: '	Antarctica/DumontDUrville	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 372,
			utc: '	UTC+10	',
			timeZone: '	Antarctica/Macquarie	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 373,
			utc: '	UTC+10	',
			timeZone: '	Asia/Ust-Nera	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 374,
			utc: '	UTC+10	',
			timeZone: '	Asia/Vladivostok	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 375,
			utc: '	UTC+10	',
			timeZone: '	Australia/Brisbane	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 376,
			utc: '	UTC+10	',
			timeZone: '	Australia/Hobart	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 377,
			utc: '	UTC+10	',
			timeZone: '	Australia/Lindeman	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 378,
			utc: '	UTC+10	',
			timeZone: '	Australia/Melbourne	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 379,
			utc: '	UTC+10	',
			timeZone: '	Australia/Sydney	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 380,
			utc: '	UTC+10	',
			timeZone: '	Pacific/Chuuk	',
			country: '	Micronesia	',
			flagCode: '	fm	',
		},
		{
			idCountry: 381,
			utc: '	UTC+10	',
			timeZone: '	Pacific/Guam	',
			country: '	Guam	',
			flagCode: '	gu	',
		},
		{
			idCountry: 382,
			utc: '	UTC+10	',
			timeZone: '	Pacific/Port_Moresby	',
			country: '	Papua New Guinea	',
			flagCode: '	pg	',
		},
		{
			idCountry: 383,
			utc: '	UTC+10	',
			timeZone: '	Pacific/Saipan	',
			country: '	Northern Mariana Islands	',
			flagCode: '	mp	',
		},
		{
			idCountry: 384,
			utc: '	UTC+10:30	',
			timeZone: '	Australia/Lord_Howe	',
			country: '	Australia	',
			flagCode: '	au	',
		},
		{
			idCountry: 385,
			utc: '	UTC+11	',
			timeZone: '	Antarctica/Casey	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 386,
			utc: '	UTC+11	',
			timeZone: '	Asia/Magadan	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 387,
			utc: '	UTC+11	',
			timeZone: '	Asia/Sakhalin	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 388,
			utc: '	UTC+11	',
			timeZone: '	Asia/Srednekolymsk	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 389,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Bougainville	',
			country: '	Papua New Guinea	',
			flagCode: '	pg	',
		},
		{
			idCountry: 390,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Efate	',
			country: '	Vanuatu	',
			flagCode: '	vu	',
		},
		{
			idCountry: 391,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Guadalcanal	',
			country: '	Solomon Islands	',
			flagCode: '	sb	',
		},
		{
			idCountry: 392,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Kosrae	',
			country: '	Micronesia	',
			flagCode: '	fm	',
		},
		{
			idCountry: 393,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Norfolk	',
			country: '	Norfolk Island	',
			flagCode: '	nf	',
		},
		{
			idCountry: 394,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Noumea	',
			country: '	New Caledonia	',
			flagCode: '	nc	',
		},
		{
			idCountry: 395,
			utc: '	UTC+11	',
			timeZone: '	Pacific/Pohnpei	',
			country: '	Micronesia	',
			flagCode: '	fm	',
		},
		{
			idCountry: 396,
			utc: '	UTC+12	',
			timeZone: '	Antarctica/McMurdo	',
			country: '	Antarctica	',
			flagCode: '	aq	',
		},
		{
			idCountry: 397,
			utc: '	UTC+12	',
			timeZone: '	Asia/Anadyr	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 398,
			utc: '	UTC+12	',
			timeZone: '	Asia/Kamchatka	',
			country: '	Russia	',
			flagCode: '	ru	',
		},
		{
			idCountry: 399,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Auckland	',
			country: '	New Zealand	',
			flagCode: '	nz	',
		},
		{
			idCountry: 400,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Fiji	',
			country: '	Fiji	',
			flagCode: '	fj	',
		},
		{
			idCountry: 401,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Funafuti	',
			country: '	Tuvalu	',
			flagCode: '	tv	',
		},
		{
			idCountry: 402,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Kwajalein	',
			country: '	Marshall Islands	',
			flagCode: '	mh	',
		},
		{
			idCountry: 403,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Majuro	',
			country: '	Marshall Islands	',
			flagCode: '	mh	',
		},
		{
			idCountry: 404,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Nauru	',
			country: '	Nauru	',
			flagCode: '	nr	',
		},
		{
			idCountry: 405,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Tarawa	',
			country: '	Kiribati	',
			flagCode: '	ki	',
		},
		{
			idCountry: 406,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Wake	',
			country: '	United States Minor Outlying Islands	',
			flagCode: '	um	',
		},
		{
			idCountry: 407,
			utc: '	UTC+12	',
			timeZone: '	Pacific/Wallis	',
			country: '	Wallis and Futuna	',
			flagCode: '	wf	',
		},
		{
			idCountry: 408,
			utc: '	UTC+12:45	',
			timeZone: '	Pacific/Chatham	',
			country: '	New Zealand	',
			flagCode: '	nz	',
		},
		{
			idCountry: 409,
			utc: '	UTC+13	',
			timeZone: '	Pacific/Apia	',
			country: '	Samoa	',
			flagCode: '	ws	',
		},
		{
			idCountry: 410,
			utc: '	UTC+13	',
			timeZone: '	Pacific/Fakaofo	',
			country: '	Tokelau	',
			flagCode: '	tk	',
		},
		{
			idCountry: 411,
			utc: '	UTC+13	',
			timeZone: '	Pacific/Kanton	',
			country: '	Kiribati	',
			flagCode: '	ki	',
		},
		{
			idCountry: 412,
			utc: '	UTC+13	',
			timeZone: '	Pacific/Tongatapu	',
			country: '	Tonga	',
			flagCode: '	to	',
		},
		{
			idCountry: 413,
			utc: '	UTC+14	',
			timeZone: '	Pacific/Kiritimati	',
			country: '	Kiribati	',
			flagCode: '	ki	',
		},
	];
